name: api-build

on:
  push:
    paths:
      - ".github/workflows/api-build.yml"
      - "api/**"
  workflow_dispatch:

jobs:
  build:
    name: build-dotnet-api
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./api
      - run: dotnet test
        working-directory: ./api
      - run: dotnet publish -c Release -o ./api/release /p:WebPublishMethod=Package
        working-directory: ./api
      - uses: actions/upload-artifact@v4
        with:
          path: ./api/release/**
          name: api
  deploy:
    name: deploy-api
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: api
      - run: ls
      - run: |
          iisreset /stop
          Copy-Item -Path .\api\release\* -Destination C:\inetpub\wwwroot\api -Recurse -Force
          iisreset /start
      
