name: api-build

on:
  push:
    paths:
      - ".github/workflows/api-build.yml"
      - "api/**"
  workflow_dispatch:

jobs:
  build:
    name: build-dotnet-api
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./api
      - run: dotnet test
        working-directory: ./api
      - run: dotnet publish -c Release -o ./api/bin /p:WebPublishMethod=Package
        working-directory: ./api
      - uses: actions/upload-artifact@v4
        with:
          path: ./api/bin/**
          name: api
      
